[package]
name = "m1n3_protocol"
version = "0.1.0"
edition = "2024.beta"

[environments]
devnet = "4f0ae125"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
m1n3_protocol = "0x0"
