import type {
  PricedShare,
  OrderBookEntry,
  OrderBookData,
  SimulatedTrade,
  MarketSimulationParams,
  DiscountCurvePoint,
} from "@/lib/types";
import {
  computeTheoreticalValue,
  computeDiscount,
  discountAtBlock,
  difficultyToWorkPh,
} from "@/lib/hashprice-utils";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Simple seeded pseudo-random for reproducibility (xorshift32). */
function seededRandom(seed: number) {
  let s = seed | 0;
  return () => {
    s ^= s << 13;
    s ^= s >> 17;
    s ^= s << 5;
    return ((s >>> 0) / 4294967296);
  };
}

/** Box-Muller transform for gaussian noise. */
function gaussian(rng: () => number, mean: number, stddev: number): number {
  const u1 = rng();
  const u2 = rng();
  const z = Math.sqrt(-2 * Math.log(u1 || 1e-10)) * Math.cos(2 * Math.PI * u2);
  return mean + z * stddev;
}

// Difficulty tiers used for mock data
const DIFFICULTY_TIERS = [1_000, 10_000, 100_000, 1_000_000];

// ---------------------------------------------------------------------------
// Scenario Presets
// ---------------------------------------------------------------------------

// Default network difficulty (~100T) and block reward for presets
const DEFAULT_NET_DIFF = 100e12;
const DEFAULT_BLOCK_REWARD_USD = 3.125 * 90_000; // 281,250 USD

export const SCENARIO_PRESETS: Record<string, MarketSimulationParams> = {
  stable: {
    networkDifficulty: DEFAULT_NET_DIFF,
    blockRewardUsd: DEFAULT_BLOCK_REWARD_USD,
    averageDiscount: 10,
    spreadBps: 150,
    tradeFrequencyPerMin: 4,
  },
  bull: {
    networkDifficulty: DEFAULT_NET_DIFF,
    blockRewardUsd: 3.125 * 120_000,
    averageDiscount: 6,
    spreadBps: 100,
    tradeFrequencyPerMin: 8,
  },
  bear: {
    networkDifficulty: DEFAULT_NET_DIFF * 1.2,
    blockRewardUsd: 3.125 * 60_000,
    averageDiscount: 18,
    spreadBps: 300,
    tradeFrequencyPerMin: 2,
  },
  volatile: {
    networkDifficulty: DEFAULT_NET_DIFF,
    blockRewardUsd: 3.125 * 95_000,
    averageDiscount: 12,
    spreadBps: 400,
    tradeFrequencyPerMin: 6,
  },
};

// ---------------------------------------------------------------------------
// Mock Listing Generator
//
// NOTE: All data generated by functions in this file is SIMULATED.
// It should be clearly labeled as "Simulated" in any UI that displays it.
// These generators serve as fallbacks until real on-chain event indexing
// (ListingPurchased, ListingCreated, ListingCanceled) replaces them.
// ---------------------------------------------------------------------------

/** @simulated Generate mock listings for visualization. Label as "Simulated" in UI. */
export function generateMockListings(
  params: MarketSimulationParams,
  chainHeight: number,
  seed = 42,
): PricedShare[] {
  const rng = seededRandom(seed);
  const count = 50 + Math.floor(rng() * 30); // 50–80 listings
  const listings: PricedShare[] = [];

  for (let i = 0; i < count; i++) {
    const tierIdx = Math.floor(rng() * DIFFICULTY_TIERS.length);
    // Add some variance within the tier (0.5x – 3x)
    const difficulty = DIFFICULTY_TIERS[tierIdx] * (0.5 + rng() * 2.5);
    const blocksUntilMature = Math.floor(rng() * 100);
    const blockHeight = chainHeight - (100 - blocksUntilMature);

    const theoUsd = computeTheoreticalValue(difficulty, params.networkDifficulty, params.blockRewardUsd);

    // Discount = base curve + gaussian noise
    const baseDiscount = discountAtBlock(blocksUntilMature, params.averageDiscount);
    const noise = gaussian(rng, 0, params.averageDiscount * 0.15);
    const finalDiscount = Math.max(0, Math.min(40, baseDiscount + noise));

    const marketPriceUsd = theoUsd * (1 - finalDiscount / 100);

    listings.push({
      id: `0x${(0xfeed0000 + i).toString(16)}`,
      seller: `0x${(0xa0000000 + Math.floor(rng() * 0xffffff)).toString(16)}`,
      difficultyAchieved: Math.round(difficulty),
      workWeight: Math.round(difficulty * 4_294_967_296),
      blockHeight,
      templateId: `0x${(0xb0000000 + (i % 5)).toString(16)}`,
      isBlock: rng() < 0.02,
      theoreticalValueUsd: theoUsd,
      marketPriceUsd: Math.max(0.001, marketPriceUsd),
      discountPct: finalDiscount,
      blocksUntilMature,
    });
  }

  return listings.sort((a, b) => a.difficultyAchieved - b.difficultyAchieved);
}

// ---------------------------------------------------------------------------
// Order Book Generator
// ---------------------------------------------------------------------------

export function generateOrderBook(
  listings: PricedShare[],
  spreadBps: number,
  seed = 99,
): OrderBookData {
  const rng = seededRandom(seed);

  if (listings.length === 0) {
    return { bids: [], asks: [], spread: 0, midpoint: 0, lastTradePrice: 0 };
  }

  // Use median listing price as reference
  const sorted = [...listings].sort((a, b) => a.marketPriceUsd - b.marketPriceUsd);
  const midIdx = Math.floor(sorted.length / 2);
  const midpoint = sorted[midIdx].marketPriceUsd;
  const halfSpread = midpoint * (spreadBps / 10_000 / 2);

  const LEVELS = 20;
  const bids: OrderBookEntry[] = [];
  const asks: OrderBookEntry[] = [];

  // Pick a representative difficulty for hashrate sizing
  const medianDiff = sorted[midIdx].difficultyAchieved;

  let bidCumulative = 0;
  for (let i = 0; i < LEVELS; i++) {
    const price = midpoint - halfSpread - (i * midpoint * 0.005);
    const ph = difficultyToWorkPh(medianDiff) * (0.5 + rng() * 2.5);
    bidCumulative += ph;
    bids.push({ price: Math.max(0.001, price), hashratePh: ph, cumulativePh: bidCumulative, side: "bid" });
  }

  let askCumulative = 0;
  for (let i = 0; i < LEVELS; i++) {
    const price = midpoint + halfSpread + (i * midpoint * 0.005);
    const ph = difficultyToWorkPh(medianDiff) * (0.5 + rng() * 2.5);
    askCumulative += ph;
    asks.push({ price, hashratePh: ph, cumulativePh: askCumulative, side: "ask" });
  }

  const lastTradePrice = midpoint + gaussian(rng, 0, halfSpread * 0.5);

  return {
    bids,
    asks,
    spread: halfSpread * 2,
    midpoint,
    lastTradePrice,
  };
}

// ---------------------------------------------------------------------------
// Trade History Generator
// ---------------------------------------------------------------------------

export function generateTradeHistory(
  params: MarketSimulationParams,
  midpoint: number,
  count = 60,
  seed = 77,
): SimulatedTrade[] {
  const rng = seededRandom(seed);
  const now = Date.now();
  const trades: SimulatedTrade[] = [];

  for (let i = 0; i < count; i++) {
    const side: "buy" | "sell" = rng() > 0.5 ? "buy" : "sell";
    const noise = gaussian(rng, 0, midpoint * (params.spreadBps / 10_000));
    const price = Math.max(0.001, midpoint + noise);

    // Use a representative difficulty for trade hashrate
    const avgDiff = 50_000;
    const ph = difficultyToWorkPh(avgDiff) * (0.5 + rng() * 2);

    // Approximate discount from average theoretical value
    const theoUsd = computeTheoreticalValue(avgDiff, params.networkDifficulty, params.blockRewardUsd);
    const disc = theoUsd > 0 ? computeDiscount(price, theoUsd) : params.averageDiscount;

    const msAgo = Math.floor(rng() * 24 * 60 * 60 * 1000); // within last 24h
    trades.push({
      price,
      hashratePh: ph,
      side,
      discountPct: Math.max(0, disc),
      timestampMs: now - msAgo,
    });
  }

  return trades.sort((a, b) => b.timestampMs - a.timestampMs);
}

// ---------------------------------------------------------------------------
// Discount Curve Points (for DiscountCurveChart)
// ---------------------------------------------------------------------------

export function generateDiscountCurve(
  networkDifficulty: number,
  blockRewardUsd: number,
  maxDiscount: number,
  referenceDifficulty = 50_000,
): DiscountCurvePoint[] {
  const points: DiscountCurvePoint[] = [];

  for (let blocks = 100; blocks >= 0; blocks--) {
    const disc = discountAtBlock(blocks, maxDiscount);
    const theoUsd = computeTheoreticalValue(referenceDifficulty, networkDifficulty, blockRewardUsd);
    const marketPrice = theoUsd * (1 - disc / 100);

    points.push({
      blocksUntilMature: blocks,
      discountPct: disc,
      theoreticalValue: theoUsd,
      marketPrice,
    });
  }

  return points;
}
